Ensure `terraform init` before downloading state file
to avoid state file overriden by blank state file

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,9 +7,13 @@ inputs:
   state_repo:
     description: 'Repository containing the Terraform state file'
     required: true
-  state_path:
-    description: 'Path to the Terraform state file in the `state_repo`'
-    required: true
+  state_path_remote:
+    description: 'Path to the Terraform state file in `state_repo`'
+    required: false
+    default: 'terraform.tfstate'
+  state_path_local:
+    description: 'Path to the Terraform state file in GitHub Actions environment'
+    required: false
     default: 'terraform.tfstate'
   action:
     description: 'Action to perform (download or upload)'
@@ -36,6 +40,19 @@ outputs:
 runs:
   using: 'composite'
   steps:
+    - name: Extract working directory from `state_path_local`
+      id: extract_workdir
+      run: |
+        workdir=$(dirname "${{ inputs.state_path_local }}")
+        echo "workdir=$workdir" >> $GITHUB_ENV
+
+    - name: Check if Terraform env is initialized
+      run: |
+        if [ ! -d "${{ env.workdir }}/.terraform" ]; then
+          echo "Error: Terraform has not been initialized. Please run 'terraform init' at `${{ env.workdir }}` before this action." >&2
+          exit 1
+        fi
+
     - name: Perform action
       run: |
         if [ "${{ inputs.action }}" = "download" ]; then
@@ -43,22 +60,22 @@ runs:
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ inputs.token }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ inputs.state_repo }}/contents/${{ inputs.state_path }} > terraform.tfstate.response
-          jq -r '.content' terraform.tfstate.response | base64 --decode > terraform.tfstate
-          echo "sha=$(jq -r '.sha' terraform.tfstate.response)" >> $GITHUB_OUTPUT
+            https://api.github.com/repos/${{ inputs.state_repo }}/contents/${{ inputs.state_path_remote }} > ${{ inputs.state_path_local }}.response
+          jq -r '.content' ${{ inputs.state_path_local }}.response | base64 --decode > ${{ inputs.state_path_local }}
+          echo "sha=$(jq -r '.sha' ${{ inputs.state_path_local }}" >> $GITHUB_OUTPUT
         elif [ "${{ inputs.action }}" = "upload" ]; then
           if [ -z "${{ inputs.sha }}" ]; then
             echo "Error: sha input is required for upload action" >&2
             exit 1
           fi
-          CONTENT=$(base64 terraform.tfstate | tr -d '\n')
+          CONTENT=$(base64 ${{ inputs.state_path_local }} | tr -d '\n')
           jq -n --arg msg "${{ inputs.message }}" --arg name "${{ inputs.committer_name }}" --arg email "${{ inputs.committer_email }}" --arg content "$CONTENT" --arg sha "${{ inputs.sha }}" '{message: $msg, committer: {name: $name, email: $email}, content: $content, sha: $sha}' > payload.json
           curl -L \
             -X PUT \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ inputs.token }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ inputs.state_repo }}/contents/${{ inputs.state_path }} \
+            https://api.github.com/repos/${{ inputs.state_repo }}/contents/${{ inputs.state_path_remote }} \
             -d @"payload.json"
         else
           echo "Error: Invalid action input, must be 'download' or 'upload'" >&2
